### PR TITLE
rename maintainers for case-insensitive filesystems

### PR DESCRIPTION
**Pull request by thaJeztah**
where maintainers===MAINTAINERS

also added a .dockerignore to prevent busting the cache
when it's not needed \o/

### CODE REVIEW

**Comment by thaJeztah** [comment]
Name is a bit boring, but meh (wanted to name if "borg" first :joy:)

**Comment by thaJeztah** [comment]
oh, let me ping someone here as well :-)

@jfrazelle @icecrime ptal

**Comment by jfrazelle** [comment]
Ah crap conflicts because I merged the other first sorry but LGTM

**Comment by thaJeztah** [comment]
yup thought that would happen; no worries, I'll rebase when I get home

**Comment by thaJeztah** [comment]
rebased, author LGTM :)

**Pull request merged**
