### PR TITLE
Add spdystream

### PR DESCRIPTION
**Pull request by thaJeztah**
Looks like this one was missing

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle :-)

**Comment by jfrazelle** [comment]
awesomeee

**Comment by thaJeztah** [comment]
oh, darn, forgot to stage boot2docker and docker-py, lolz

**Comment by dnephin** [comment]
libkv as well?

**Comment by thaJeztah** [comment]
@dnephin yes, there are more to be added, some repos don't have a maintainers file, I noticed (libkv being one of them). I'll have another look at the other repos as well :+1:

**Pull request merged**
