### PR TITLE
Update project maintainers

### PR DESCRIPTION
**Pull request by vdemeester**
This updates project maintainer for : `docker/engine-api` and `docker/docker`.

@moxiegirl @thaJeztah Are the changes for *Curators* and *Docs maintainers* normal ? :angel: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vdemeester yes, the "Curators" and "Docs maintainers" sections aren't generated properly by the script; the script hasn't been modified yet to make it work with *multiple* projects/repos having a "Docs maintainers" or "Curators" section, so the last repository containing one will overwrite the previous ones (instead of merging the people in those).

Last time I updated, I just edited that manually, but we should update the script so that it works :smile:

**Comment by vdemeester** [comment]
@thaJeztah Ok :stuck_out_tongue: I'll take a look at the script too then :wink:

**Comment by vdemeester** [comment]
@thaJeztah updated the code and re-ran it :angel:

**Comment by thaJeztah** [comment]
nice! LGTM

**Pull request merged**
